import os
from datetime import datetime
from webscanner.report.base import ReportGenerator
from webscanner.utils.scoring import risk_level, risk_emoji


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>WebSec Scanner Report - {target}</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f1117; color: #e1e4e8; line-height: 1.6; }}
  .container {{ max-width: 1100px; margin: 0 auto; padding: 20px; }}
  .header {{ background: linear-gradient(135deg, #1a1d29, #0d1117); padding: 40px; border-radius: 12px; margin-bottom: 24px; border: 1px solid #30363d; }}
  .header h1 {{ font-size: 28px; color: #58a6ff; margin-bottom: 8px; }}
  .header .meta {{ color: #8b949e; font-size: 14px; }}
  .score-box {{ display: inline-block; padding: 20px; border-radius: 12px; text-align: center; margin: 16px 0; min-width: 200px; }}
  .score-box .score {{ font-size: 48px; font-weight: bold; }}
  .score-box .label {{ font-size: 16px; margin-top: 8px; }}
  .summary-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin-bottom: 24px; }}
  .summary-card {{ background: #161b22; padding: 20px; border-radius: 8px; border: 1px solid #30363d; }}
  .summary-card .number {{ font-size: 32px; font-weight: bold; }}
  .summary-card .label {{ color: #8b949e; font-size: 13px; }}
  .critical {{ color: #f85149; }} .high {{ color: #d29922; }} .medium {{ color: #58a6ff; }} .low {{ color: #8b949e; }} .info {{ color: #3fb950; }}
  .finding {{ background: #161b22; padding: 20px; border-radius: 8px; margin-bottom: 12px; border: 1px solid #30363d; }}
  .finding h3 {{ margin-bottom: 8px; }}
  .finding .sev-badge {{ display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 12px; font-weight: 600; text-transform: uppercase; margin-bottom: 8px; }}
  .sev-critical {{ background: #f8514922; color: #f85149; border: 1px solid #f85149; }}
  .sev-high {{ background: #d2992222; color: #d29922; border: 1px solid #d29922; }}
  .sev-medium {{ background: #58a6ff22; color: #58a6ff; border: 1px solid #58a6ff; }}
  .sev-low {{ background: #8b949e22; color: #8b949e; border: 1px solid #8b949e; }}
  .sev-info {{ background: #3fb95022; color: #3fb950; border: 1px solid #3fb950; }}
  .finding .field {{ margin: 4px 0; font-size: 14px; }}
  .finding .field-label {{ color: #8b949e; }}
  table {{ width: 100%; border-collapse: collapse; margin: 16px 0; }}
  th, td {{ padding: 10px 14px; text-align: left; border-bottom: 1px solid #30363d; }}
  th {{ color: #8b949e; font-weight: 600; }}
  .tech-tag {{ display: inline-block; padding: 4px 10px; background: #1f2937; border-radius: 6px; margin: 2px; font-size: 13px; }}
  .footer {{ color: #8b949e; font-size: 12px; text-align: center; padding: 20px; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>Web Security Scan Report</h1>
    <div class="meta">Target: {target} | Mode: {mode} | Date: {date}</div>
    <div class="meta">Duration: {duration}s | Pages Crawled: {pages}</div>
    <div class="score-box" style="background: {bg_color};">
      <div class="score">{score}</div>
      <div class="label">/ 100 - {risk_label}</div>
      <div style="font-size: 32px; margin-top: 8px;">{risk_emoji}</div>
    </div>
  </div>

  <h2>Summary</h2>
  <div class="summary-grid">
    <div class="summary-card">
      <div class="number critical">{critical}</div>
      <div class="label">Critical</div>
    </div>
    <div class="summary-card">
      <div class="number high">{high}</div>
      <div class="label">High</div>
    </div>
    <div class="summary-card">
      <div class="number medium">{medium}</div>
      <div class="label">Medium</div>
    </div>
    <div class="summary-card">
      <div class="number low">{low}</div>
      <div class="label">Low</div>
    </div>
    <div class="summary-card">
      <div class="number info">{info}</div>
      <div class="label">Info</div>
    </div>
    <div class="summary-card">
      <div class="number">{total}</div>
      <div class="label">Total Findings</div>
    </div>
  </div>

  {tech_section}

  <h2>Findings</h2>
  {findings_html}

  <div class="footer">
    Generated by WebSec Scanner | {date}
  </div>
</div>
</body>
</html>"""


class HTMLReport(ReportGenerator):
    def generate(self, result: ScanResult, output_path: str = ""):
        score = result.security_score
        label = risk_level(score)
        emoji = risk_emoji(score)

        if score >= 90:
            bg = "#1a3a2a"
        elif score >= 75:
            bg = "#3a3a1a"
        elif score >= 50:
            bg = "#3a2a1a"
        elif score >= 25:
            bg = "#3a1a1a"
        else:
            bg = "#1a1a1a"

        tech_html = ""
        if result.tech_stack:
            tags = "".join(f'<span class="tech-tag">{t}</span>' for t in result.tech_stack)
            tech_html = f"<h2>Technology Stack</h2><div>{tags}</div>"

        findings_html = ""
        for severity in ["critical", "high", "medium", "low", "info"]:
            items = [f for f in result.findings if f.severity == severity]
            if not items:
                continue
            findings_html += f"<h3 class='{severity}'>{severity.upper()} ({len(items)})</h3>"
            for f in items:
                findings_html += f"""
                <div class="finding">
                  <span class="sev-badge sev-{severity}">{severity}</span>
                  <h3>{f.name}</h3>
                  <div class="field"><span class="field-label">Description:</span> {f.description}</div>"""
                if f.url:
                    findings_html += f'<div class="field"><span class="field-label">URL:</span> {f.url}</div>'
                if f.evidence:
                    findings_html += f'<div class="field"><span class="field-label">Evidence:</span> {f.evidence[:200]}</div>'
                if f.recommendation:
                    findings_html += f'<div class="field"><span class="field-label">Recommendation:</span> {f.recommendation}</div>'
                if f.cve_id:
                    findings_html += f'<div class="field"><span class="field-label">CVE:</span> {f.cve_id}</div>'
                if f.cwe_id:
                    findings_html += f'<div class="field"><span class="field-label">CWE:</span> {f.cwe_id}</div>'
                if f.cvss:
                    findings_html += f'<div class="field"><span class="field-label">CVSS:</span> {f.cvss}</div>'
                if f.confidence:
                    findings_html += f'<div class="field"><span class="field-label">Confidence:</span> {f.confidence}</div>'
                findings_html += "</div>"

        html = HTML_TEMPLATE.format(
            target=result.target,
            mode=result.mode.upper(),
            date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            duration=f"{result.scan_duration:.2f}",
            pages=result.pages_crawled,
            score=score,
            risk_label=label,
            risk_emoji=emoji,
            bg_color=bg,
            critical=result.critical_count,
            high=result.high_count,
            medium=result.medium_count,
            low=result.low_count,
            info=result.info_count,
            total=result.total_findings,
            tech_section=tech_html,
            findings_html=findings_html,
        )

        if not output_path:
            safe_name = result.target.replace("://", "_").replace("/", "_").replace(":", "_").replace("?", "_").replace("&", "_")
            output_path = f"scan_report_{safe_name}.html"
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
        return output_path
